M48
; DRILL file {KiCad 9.0.0} date 2025-06-29T21:09:45-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-29T21:09:45-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X5.8185Y-1.111
T2
X4.7146Y-9.5517
X6.2697Y-9.5517
M30
